config/routes.rb
Rails.application.routes.draw do
  resources :gossips do
    resources :comments
    resources :likes, only: [ :create, :destroy ]
  end

  resources :sessions, only: [ :new, :create, :destroy ]
  resources :users

  # Les routes `get` en dessous
  get "city/cityview/:id", to: "city#cityview"
  get "show/:user", to: "static_profil#profil"
  get "static_welcome/welcome/:hide", to: "static_welcome#welcome"
  get "gossip/:id", to: "static_gossip#gossip"
  get "static_contact/contact"
  get "static_team/team"

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments

  validates :title, presence: true, length: { minimum: 3, maximum: 14 }
  validates :content, presence: true

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip


  validates :user_id, uniqueness: { scope: :gossip_id }
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
  has_and_belongs_to_many :recipients, class_name: 'User', join_table: 'private_messages_users'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :city
  has_many :gossips
  has_many :Comments
  has_many :sent_messages, foreign_key: "sender_id", class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: "recipient_id", class_name: "PrivateMessage"
  has_many :likes, dependent: :destroy
  has_many :liked_gossips, through: :likes, source: :gossip
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def cityview
    @city = City.find(params[:id])
    @gossips = @city.gossips
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user
  def index
    @gossip = Gossip.all
    @tags = Tag.all
  end

  def show
    @gossip = Gossip.find(params[:id])
  end


  def new
    @gossip = Gossip.new
  end
  def create
    @gossip = Gossip.create(
      content: params["gossip_content"],
      title: params["gossip_title"],
      user_id: current_user.id
    ) # avec xxx qui sont les données obtenues à partir du formulaire
    if @gossip.save # essaie de sauvegarder en base @gossip
      redirect_to gossips_path, notice: "Gossip créé avec succès."
    else
     render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(gossip_params)
      redirect_to @gossip, notice: "Potin bien mis à jour !"
    else
      render :edit
    end
  end
  def destroy
    @gossip = Gossip.find_by(id: params[:id])
    if current_user == @gossip.user
      @gossip.likes.destroy_all
      @gossip.comments.destroy_all
      @gossip.tags.destroy_all
      @gossip.destroy
      flash[:notice] = "Gossip supprimé avec succès."
      redirect_to gossips_path
    else
      flash[:danger] = "Vous n'avez pas le droit de supprimer ce potin."
      redirect_to gossips_path
    end
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content) # Permet les attributs title et content
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/static_team_helper.rb
module StaticTeamHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossips/edit.html.erb
<h1>Editer le potin</h1>

<%= form_with(model: @gossip, local: true) do |form| %>
  <% if @gossip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gossip.errors.count, "erreur") %> empêchent la mise à jour du potin :</h2>
      <ul>
        <% @gossip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, value: @gossip.title %> <!-- Remplit le champ avec le titre actuel -->
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, value: @gossip.content %> <!-- Remplit le champ avec le contenu actuel -->
  </div>

  <div class="actions">
    <%= form.submit "Mettre à jour" %>
  </div>
<% end %>

app/views/gossips/index.html.erb
<html>
  <head>
    <title>Créer un potin</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

  <header>
    <div class="menu">

    <%= link_to "Home", gossips_path, class: "lien" %>
    <%= link_to "Contact", static_contact_contact_path, class: "lien" %>
    <%=  link_to "Team", static_team_team_path, class: "lien" %>
      <a class="btnnew" href="/gossips/new">
        New gossip
        <%= image_tag "plus.png", class: "plusimg", alt: "Plus" %>
      </a>



    </div>
  </header>

  <div class="container">
    <div class="profilsection">
     <div class="profil">
      <%= image_tag "thp.png", class: "bannprofil", alt: "Plus" %>
      <div class="infoprofil">
        <div class="nbfollower">
          <p class="nb">1984</p>
          <p class="name">Followers</p>
        </div>
        <%= image_tag "utilisateur.png", class: "profilimg", alt: "Plus" %>
         <div class="nbfollowing">
          <p class="nb">1298</p>
          <p class="name">Following</p>
        </div>
      </div>
      <p class="username"><%= current_user.last_name %></p>
      <p class="lienuser">@<%= current_user.last_name %><%= current_user.first_name %></p>
      <p class="presentationuser"><%= current_user.description %></p>
      <div class="trait"></div>

      <%= form_with(url: session_path(session[:user_id]), method: :delete, local: true) do %>
      <%= submit_tag "Se déconnecter", class: "btnvisit", data: { confirm: 'Êtes-vous sûr de vouloir vous déconnecter ?' } %>
      <% end %>
      
     </div>
    <p class="tagtitle">Tag :</p>

<% @tags.each_slice(3) do |tag_group| %> <!-- Divise les tags en groupes de 3 -->
  <div class="tag-row">
    <% tag_group.each do |tag| %>
      <span class="tag-item"><%= tag.title %></span>
    <% end %>
  </div>
<% end %>

    </div>

    <div class="gossipsection">

      <div class="userlist">
      <% @users = User.joins(:gossips).distinct %>
      <% @users.each do |user| %>
        <div class="profilbd">
           <% if user.first_name == "anonymous" %>
        <%= image_tag "utilisateur.png", class: "userbdimg", alt: "Anonymous" %>
      <% else %>
        <%= image_tag "utilisateur.png", class: "userbdimg", alt: "User" %>
      <% end %>
        <p class="userbd"><%= user.first_name %></p>
        </div>
      <% end %>
      </div>

      <div class="formaccueil">
      
<form action="<%= gossips_path %>" method="POST">
  <div class="headerform">
 <%= image_tag "utilisateur.png", class: "profilimgform", alt: "Plus" %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div class ="inputdiv">
  <input class="titreinput" type="text" name="gossip_title" placeholder="Entrez un titre">
 <textarea class="textinput" name="gossip_content" placeholder="Entrez votre gossip ici"></textarea>
<br>
  </div>
   </div>
  <p class="margin"><input class="btnform" type="submit" value="Envoyer"></p>
</form>
      </div>

      <div class="divderniers">
        <div class="headerderniers">
         <%= image_tag "utilisateur.png", class: "profilimgform", alt: "Plus" %>
         <div class="infouserdernier">
          <p class="lienprofilderniers">@FlorianTribout <%= image_tag "verifier.png", class: "verif", alt: "Plus" %></p>
          <div class="namederniers">Florian Tribout<p class="time"></p><p class="infotime">1 hr ago</p></div>
          </div>
          
        </div>
        <p class="contenuderniers">🎉 J'ai commencé ma formation chez THP et je suis déjà fan du code ! 🚀💻 Hâte d'apprendre et de créer des choses incroyables !</p>
        <%= image_tag "thp.png", class: "postthp", alt: "Plus" %>
         <div class="commdiv">

         <span class="align"> <%= image_tag "commentaire.png", class: "comimg", alt: "com" %> 35</span>
         </div>
         <div class="trait"></div>
        <input class="comminput" type="text" placeholder="Entrez un commentaire">
      </div>
     
    </div>

   <div class="recentsection">
  <div class="recentdiv">
    <p class="titlerecent">Recent Gossips</p>

    <div class="gossip-container">
      <% @gossip.reverse.each  do |gossip| %>
        <div class="gossiphome">
          <div class="headergossip">
            <div class="imgusertext">
             
        <%= image_tag "utilisateur.png", class: "userecent", alt: "User" %>

              <p class="infogossip">@<%= gossip.user.last_name %></p>
            </div>
            <p class="infogossip">#<%= gossip.id %> </p>
            </div>





          <p class="textgossip"><%= gossip.content %></p>
          
          
         

<div class="likecomm">
<% if current_user %>
  <div class="like">
    <% like = gossip.likes.find_by(user: current_user) %>
    <% if like %>
      <%= form_with(url: gossip_like_path(gossip, like), method: :delete, local: true, id: "unlike-form-#{like.id}") do %>
        <div>
          <%= link_to image_tag("coeurrouge.png", alt: "Unlike", class: "coeur"), "#", 
            onclick: "event.preventDefault(); document.getElementById('unlike-form-#{like.id}').submit();" %>
            
        </div>
      <% end %>
    <% else %>
      <%= form_with(url: gossip_likes_path(gossip), method: :post, local: true, id: "like-form-#{gossip.id}") do %>
        <div>
          <%= link_to image_tag("coeurgris.png", alt: "Like", class: "coeur"), "#", 
            onclick: "event.preventDefault(); document.getElementById('like-form-#{gossip.id}').submit();" %>
        </div>
      <% end %>
    <% end %>
    <p><%= gossip.likes.count %></p>
  </div>
<% end %>
 <%= image_tag "commentaire.png", class: "comimgindex", alt: "Plus" %>
     <p><%= gossip.comments.count %> </p>
     <%= link_to "Voir", "/gossips/#{gossip.id}", class: "btn" %>
</div>














          
        </div>
      <% end %>
    </div>
  </div>
</div>












</body>
</html>

app/views/gossips/new.html.erb
<html>
  <head>
    <title>Créer un potin</title>
    <%= stylesheet_link_tag 'new', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

  <header>
    <div class="menu">

    <%= link_to "Home", gossips_path, class: "lien" %>
    <%= link_to "Contact", static_contact_contact_path, class: "lien" %>
    <%=  link_to "Team", static_team_team_path, class: "lien" %>
      <a class="btnnew" href="/gossips/new">
        New gossip
        <%= image_tag "plus.png", class: "plusimg", alt: "Plus" %>
      </a>
    </div>
  </header>

<h1>Creer un Potin</h1>

<form action="<%= gossips_path %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="text" name="gossip_title" placeholder="Entrez un titre">
  <input type="text" name="gossip_content" placeholder="Entrez votre gossip ici">
  <input type="submit" value="Valider">
</form>

</body>
</html>

app/views/gossips/show.html.erb
<html>
  <head>
    <title>Créer un potin</title>
    <%= stylesheet_link_tag 'gossip', media: 'all', 'data-turbolinks-track': 'reload' %>

   </head>
  <body>

  <header>
    <div class="menu">

    <%= link_to "Home", gossips_path, class: "lien" %>
    <a class="lien">Gossip</a>
    <%= link_to "Contact", static_contact_contact_path, class: "lien" %>
    <%=  link_to "Team", static_team_team_path, class: "lien" %>
      <a class="btnnew" href="/gossips/new">
        New gossip
        <%= image_tag "plus.png", class: "plusimg", alt: "Plus" %>
      </a>

    </div>
  </header>


 <div class="gossippages">
      <div class="headergossip">
      <div class="imgusertext">
      <%= image_tag "utilisateur.png", class: "userbdimgrecent", alt: "Plus" %>
      <%= link_to "@#{@gossip.user.first_name}", "/show/#{@gossip.id}", class: "infogossip" %>
      </div>
      <p class="idgossip">#<%= @gossip.id %> </p>
      </div>
      <p class="title"><%= @gossip.title%></p>
      <p class="textgossip"><%= @gossip.content %></p>
      


     <% @gossip.comments.each do |comment| %>
       <%= comment.user.first_name %>:<%= comment.content%>
       <% if current_user == comment.user %>
       <%= link_to "modifier comment", "/gossips/#{@gossip.id}/comments/#{comment.id}", class: "infogossip" %>
       <% else %>
<% end %>
       </br>
     <% end %>



  <%= form_with(url: gossip_comments_path(@gossip), method: :post) do %>
  <%= label_tag :content, "Ajouter un commentaire :" %>
  <%= text_field_tag :comment_content, nil, placeholder: "Entrez votre commentaire" %>
  <%= submit_tag "Valider" %>
<% end %>

<% if current_user %>
  <div class="like">
    <% like = @gossip.likes.find_by(user: current_user) %>
    
    <% if like %>
      <%= form_with(url: gossip_like_path(@gossip, like), method: :delete, local: true, id: "unlike-form-#{like.id}") do %>
        <div>
          <%= link_to image_tag("coeurrouge.png", alt: "Unlike", class: "coeur"), "#", 
            onclick: "event.preventDefault(); document.getElementById('unlike-form-#{like.id}').submit();" %>
        </div>
      <% end %>
    <% else %>
      <%= form_with(url: gossip_likes_path(@gossip), method: :post, local: true, id: "like-form-#{@gossip.id}") do %>
        <div>
          <%= link_to image_tag("coeurgris.png", alt: "Like", class: "coeur"), "#", 
            onclick: "event.preventDefault(); document.getElementById('like-form-#{@gossip.id}').submit();" %>
        </div>
      <% end %>
    <% end %>
    
    <p><%= @gossip.likes.count %></p>
  </div>
<% end %>








      <p class="city">Ecrit depuis : 
        <%= link_to "#{@gossip.user.city.name}", "/city/cityview/#{@gossip.user.city.id}", class: "infogossip" %>
     </p>

<% if current_user == @gossip.user %>
  <%= link_to "Éditer", edit_gossip_path(@gossip), class: "infogossip" %>
  
  <a href="<%= gossip_path(@gossip) %>" class="btn" onclick="event.preventDefault(); if(confirm('Êtes-vous sûr de vouloir supprimer ce potin ?')) { document.getElementById('delete-form-<%= @gossip.id %>').submit(); }">Supprimer</a>
  
  <%= form_with(model: @gossip, method: :delete, local: true, id: "delete-form-#{@gossip.id}", style: "display: none;") do |form| %>
  <% end %>
<% else %>
<% end %>


</div>





</body>
</html>