config/routes.rb
Rails.application.routes.draw do
  resources :gossips do
    resources :comments
    resources :likes, only: [ :create, :destroy ]
  end

  resources :sessions, only: [ :new, :create, :destroy ]
  resources :users

  # Les routes `get` en dessous
  get "city/cityview/:id", to: "city#cityview"
  get "show/:user", to: "static_profil#profil"
  get "static_welcome/welcome/:hide", to: "static_welcome#welcome"
  get "gossip/:id", to: "static_gossip#gossip"
  get "static_contact/contact"
  get "static_team/team"

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments

  validates :title, presence: true, length: { minimum: 3, maximum: 14 }
  validates :content, presence: true

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip


  validates :user_id, uniqueness: { scope: :gossip_id }
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
  has_and_belongs_to_many :recipients, class_name: 'User', join_table: 'private_messages_users'
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :city
  has_many :gossips
  has_many :Comments
  has_many :sent_messages, foreign_key: "sender_id", class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: "recipient_id", class_name: "PrivateMessage"
  has_many :likes, dependent: :destroy
  has_many :liked_gossips, through: :likes, source: :gossip
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def cityview
    @city = City.find(params[:id])
    @gossips = @city.gossips
  end
end

app/controllers/static_team_controller.rb
class StaticTeamController < ApplicationController
  def team
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/static_team_helper.rb
module StaticTeamHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_team/team.html.erb
<html>
  <head>
    <title>Notre équipe</title>
    <%= stylesheet_link_tag 'team', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  </head>
  <body>
    <header>
      <div class="menu">
        <%= link_to "Home", gossips_path, class: "lien" %>
        <%= link_to "Contact", static_contact_contact_path, class: "lien" %>
        <%= link_to "Team", static_team_team_path, class: "lien" %>
          <a class="btnnew" href="/gossips/new">
        New gossip
        <%= image_tag "plus.png", class: "plusimg", alt: "Plus" %>
      </a>
      </div>
    </header>

    <main>
      <h1 class="team-title">Rencontrez notre équipe</h1>

      <div class="team-member">
        <div class="card">
          <h2>Florian T</h2>
          <p>Notre expert en CSS, qui manie son code tel un peintre armé de son pinceau !
          <br>
          Avec lui, chaque ligne de style ajoute une touche de magie, 
          transformant la toile du front-end en un design inspiré
          <br>
          (et ça, sans même invoquer Bootstrap) !</p>
        </div>
      </div>

      <div class="team-member">
        <div class="card">
          <h2>Florian E</h2>
          <p>Maître des bases de données, il s'assure que chaque potin est bien gardé dans les entrailles de PostgreSQL.
          <br>
           Parmi nos potins du jour, on raconte que Florian E. a perfectionné son doigté tel un pianiste,
            à force de taper frénétiquement des lignes de code, 
            encouragé avec enthousiasme par Charlie et Florian T., 
            qui l’ont placé aux commandes de notre session Live Share.</p>
        </div>
      </div>

      <div class="team-member">
        <div class="card">
          <h2>Caroline</h2>
          <p>Sous les conseils avisés de Florian T., Caroline rêve d' insuffler à chaque page un petit côté irrésistible,
          <br>
           et tout ça, uniquement en CSS ! 
           <br>
          
          Caroline a un faible pour les ambiances tamisées : 
          <br>
          si une page ne se révèle pas dans l'obscurité, 
          <br>
          c’est qu’elle n’est pas encore prête à dévoiler tous ses charmes.</p>
        </div>
      </div>

      <div class="team-member">
        <div class="card">
          <h2>Charlie</h2>
          <p>Charlie, éclaireur bienveillant et explorateur aguerri dans les contrées de VS Code, 
          <br>
          sous son œil vigilant, même les lignes les plus capricieuses se laissent apprivoiser.</p>
        </div>
      </div>
      
      <p class="team-message">
      Ensemble, nous formons l'équipe de The Gossip Project, prête à partager le meilleur des potins, pour le plaisir des curieux ! 
      <span class="emoji">😇</span>
  </p>
  
      </main>
  </body>
</html>